/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import newpackage.Empleado;
import newpackage.Menu;
import newpackage.Sucursal;
import newpackage.Ministerio;

/**
 *
 * @author bajog
 */
public class AgregarEmpleado extends javax.swing.JFrame {

    public AgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        lblAgregarEmpleado = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblRutEmpleado = new javax.swing.JLabel();
        lblFechaNacimientoEmpleado = new javax.swing.JLabel();
        lblCargoEmpleado = new javax.swing.JLabel();
        lblSalarioEmpleado = new javax.swing.JLabel();
        lblMinisterioEmpleado = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        txtRutEmpleado = new javax.swing.JTextField();
        txtFechaNacimientoEmpleado = new javax.swing.JTextField();
        txtSalarioEmpleado = new javax.swing.JTextField();
        lblFormatoFecha = new javax.swing.JLabel();
        boxMinisterios = new javax.swing.JComboBox<>();
        btnAgregarEmpleado = new javax.swing.JButton();
        btnVolverMenuEmpleados = new javax.swing.JButton();
        lblFormatoRut = new javax.swing.JLabel();
        boxCargo = new javax.swing.JComboBox<>();
        lblMensajeEmergente = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAgregarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblAgregarEmpleado.setText("Agregar Empleado");

        lblNombreEmpleado.setText("Nombre:");

        lblRutEmpleado.setText("Rut:");

        lblFechaNacimientoEmpleado.setText("Fecha Nacimiento:");

        lblCargoEmpleado.setText("Cargo:");

        lblSalarioEmpleado.setText("Salario:");

        lblMinisterioEmpleado.setText("Ministerio:");

        txtNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpleadoActionPerformed(evt);
            }
        });

        lblFormatoFecha.setForeground(new java.awt.Color(102, 102, 102));
        lblFormatoFecha.setText("(YYYY-MM-DD)");

        boxMinisterios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione (...)", "Ministerio del interior y seguridad pública", "Ministerio de Relaciones Exteriores", "Ministerio de defensa nacional", "Ministerio de Hacienda", "Secretaría general de la Presidencia", "Secretaría general de gobierno", "Ministerio de Economía", "Fomento y Turismo", "Ministerio de desarrollo social", "Ministerio de Educación", "Ministerio de Justicia y derechos humanos", "Ministerio de Trabajo y previsión social", "Ministerio de Obras Públicas", "Ministerio de salud", "Ministerio de vivienda y urbanismo", "Ministerio de agricultura", "Ministerio de Mínería", "Ministerio de transporte y comunicaciones", "Ministerio de Bienes nacionales", "Ministerio de energía", "Ministerio de Medioambiente", "Ministerio del deporte", "Ministerio de la mujer y la equidad de género", "Ministerio de las culturas, las artes y el Patrimonio cultural" }));

        btnAgregarEmpleado.setText("Agregar");
        btnAgregarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarEmpleadoMouseClicked(evt);
            }
        });

        btnVolverMenuEmpleados.setText("Volver");
        btnVolverMenuEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMenuEmpleadosMouseClicked(evt);
            }
        });

        lblFormatoRut.setForeground(new java.awt.Color(102, 102, 102));
        lblFormatoRut.setText("(ej. 12.345.678-9)");

        boxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione (...)", "Ministro/a", "Subsecretaría", "Asesoría", "Jefe de División", "Jefe de Departamento", "Jefe de Sección", "Jefe de Oficina", "Secretario/a Regional Ministerial (SEREMI)", "Personal Administrativo", "Personal de Prensa y Comunicaciones", "Personal Tecnologia", "Personal Auxiliar" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblMensajeEmergente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAgregarEmpleado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblNombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblRutEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFechaNacimientoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCargoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblSalarioEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMinisterioEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(btnVolverMenuEmpleados)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxMinisterios, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFechaNacimientoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRutEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFormatoFecha)
                                    .addComponent(lblFormatoRut))))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAgregarEmpleado)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAgregarEmpleado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEmpleado)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutEmpleado)
                    .addComponent(txtRutEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormatoRut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaNacimientoEmpleado)
                    .addComponent(txtFechaNacimientoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFormatoFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinisterioEmpleado)
                    .addComponent(boxMinisterios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoEmpleado)
                    .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalarioEmpleado)
                    .addComponent(txtSalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(lblMensajeEmergente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolverMenuEmpleados)
                    .addComponent(btnAgregarEmpleado))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpleadoActionPerformed

    private void btnVolverMenuEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMenuEmpleadosMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MenuEmpleados.iniciar();
    }//GEN-LAST:event_btnVolverMenuEmpleadosMouseClicked

    private void btnAgregarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarEmpleadoMouseClicked
        // Recuperar los datos de los campos de texto
        String nombre = txtNombreEmpleado.getText().trim();
        String rut = txtRutEmpleado.getText().trim();
        String rutFormateado = formatearRut(rut);
        txtRutEmpleado.setText(rutFormateado);  // Actualizar el campo de texto con el formato
        
        String fechaNacimientoTexto = txtFechaNacimientoEmpleado.getText().trim();
        String salarioTexto = txtSalarioEmpleado.getText().trim();

        // Verificar que todos los campos obligatorios estén completos
        if (nombre.isEmpty() || rut.isEmpty() || fechaNacimientoTexto.isEmpty() || salarioTexto.isEmpty()) {
            lblMensajeEmergente.setText("Por favor, complete todos los campos obligatorios.");
            lblMensajeEmergente.setForeground(Color.red);
            return;  // Detener la ejecución si hay campos vacíos
        }

        LocalDate fechaNacimiento = obtenerFechaVistas(fechaNacimientoTexto);

        // Si la fecha es inválida (es decir, si obtenerFechaVistas retornó null), se detiene la ejecución
        if (fechaNacimiento == null) {
            return;  // No continúa si la fecha es inválida
        }

        LocalDate fechaContrato = LocalDate.now();
        String ministerio = boxMinisterios.getSelectedItem().toString();
        String cargo = boxCargo.getSelectedItem().toString();
        double salario = Double.parseDouble(salarioTexto);

        // Crear el empleado con los datos obtenidos
        Empleado empleado = new Empleado(nombre, rutFormateado, fechaNacimiento, fechaContrato, cargo, salario, ministerio);

        // Intentar agregar el empleado a los registros
        if (Menu.agregarRegistro(empleado)) {
            // Si se agregó correctamente, muestra el mensaje de éxito
            lblMensajeEmergente.setText("Empleado agregado correctamente");
            lblMensajeEmergente.setForeground(Color.green.darker().darker().darker());

            // Limpiar los campos de texto después de agregar
            limpiarCampos();
        } else {
            // Si no se pudo agregar (por ejemplo, si el empleado ya existe)
            lblMensajeEmergente.setText("El empleado ya existe");
            lblMensajeEmergente.setForeground(Color.red.darker().darker().darker());
        }
    }//GEN-LAST:event_btnAgregarEmpleadoMouseClicked

    private void limpiarCampos() {
        txtNombreEmpleado.setText("");
        txtRutEmpleado.setText("");
        txtFechaNacimientoEmpleado.setText("");
        txtSalarioEmpleado.setText("");
        boxMinisterios.setSelectedIndex(0);  // Restablecer a la primera opción
        boxCargo.setSelectedIndex(0);        // Restablecer a la primera opción
}
    
            
    
    /**
     */
    public static void iniciar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEmpleado().setVisible(true);
            }
        });
    }
    
    public LocalDate obtenerFechaVistas(String txtFecha) {
        lblMensajeEmergente.setText("");  // Limpia cualquier mensaje anterior
        LocalDate fecha = null;
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        try {
            // Intenta parsear la fecha ingresada por el usuario
            fecha = LocalDate.parse(txtFecha, formatter);
        } catch (DateTimeParseException e) {
            // Si ocurre un error de formato, muestra el mensaje en rojo y retorna null
            lblMensajeEmergente.setText("Formato de Fecha inválido. Use YYYY-MM-DD.");
            lblMensajeEmergente.setForeground(Color.red.darker().darker().darker());
            return null;  // Retorna null si la fecha es inválida
        }
        return fecha;  // Retorna la fecha válida
    }
    
    public static String formatearRut(String rut) {
        // Eliminar cualquier caracter que no sea número o K (si es dígito verificador)
        rut = rut.replace(".", "").replace("-", "");

        if (rut.length() < 2) {
            return rut; // No formatear si es demasiado corto
        }

        // Separar el dígito verificador del número
        String cuerpo = rut.substring(0, rut.length() - 1);
        String verificador = rut.substring(rut.length() - 1);

        // Agregar puntos al cuerpo del RUT
        StringBuilder rutFormateado = new StringBuilder();
        for (int i = cuerpo.length() - 1, j = 1; i >= 0; i--, j++) {
            rutFormateado.insert(0, cuerpo.charAt(i));
            if (j % 3 == 0 && i > 0) {
                rutFormateado.insert(0, '.');
            }
        }

        // Agregar el guion y el dígito verificador
        rutFormateado.append("-").append(verificador);

        return rutFormateado.toString();
    }
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCargo;
    private javax.swing.JComboBox<String> boxMinisterios;
    private javax.swing.JButton btnAgregarEmpleado;
    private javax.swing.JButton btnVolverMenuEmpleados;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregarEmpleado;
    private javax.swing.JLabel lblCargoEmpleado;
    private javax.swing.JLabel lblFechaNacimientoEmpleado;
    private javax.swing.JLabel lblFormatoFecha;
    private javax.swing.JLabel lblFormatoRut;
    private javax.swing.JLabel lblMensajeEmergente;
    private javax.swing.JLabel lblMinisterioEmpleado;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblRutEmpleado;
    private javax.swing.JLabel lblSalarioEmpleado;
    private javax.swing.JTextField txtFechaNacimientoEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtRutEmpleado;
    private javax.swing.JTextField txtSalarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
