/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controlador.Reporte;
import java.awt.Color;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import newpackage.Empleado;
import newpackage.Menu;
import newpackage.Sucursal;

/**
 *
 * @author bajog
 */
public class EditarEmpleado extends javax.swing.JFrame {

    private Empleado empleado;
    private Border borderRed, borderGreen;
    
    public EditarEmpleado(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        txtNombreEmpleado.setText(empleado.getNombre());
        txtRutEmpleado.setText(empleado.getRut());
        boxMinisterio.setSelectedItem(empleado.getDepartamento());
        boxCargo.setSelectedItem(empleado.getCargo());
        txtSalarioEmpleado.setText(Double.toString(empleado.getSalario()));
        borderRed = BorderFactory.createLineBorder(Color.red, 2);
        borderGreen=BorderFactory.createLineBorder(Color.green, 2);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModificarEmpleado = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        lblRutEmpleado = new javax.swing.JLabel();
        txtRutEmpleado = new javax.swing.JTextField();
        lblMinisterioEmpleado = new javax.swing.JLabel();
        lblCargoEmpleado = new javax.swing.JLabel();
        boxMinisterio = new javax.swing.JComboBox<>();
        boxCargo = new javax.swing.JComboBox<>();
        lblSalarioEmpleado = new javax.swing.JLabel();
        txtSalarioEmpleado = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblMensajeEmergente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblModificarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblModificarEmpleado.setText("Modificar Empleado");

        lblNombreEmpleado.setText("Nombre:");

        txtNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpleadoActionPerformed(evt);
            }
        });

        lblRutEmpleado.setText("Rut:");

        txtRutEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutEmpleadoActionPerformed(evt);
            }
        });

        lblMinisterioEmpleado.setText("Ministerio:");

        lblCargoEmpleado.setText("Cargo:");

        boxMinisterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione (...)", "Ministerio del interior y seguridad pública", "Ministerio de Relaciones Exteriores", "Ministerio de defensa nacional", "Ministerio de Hacienda", "Secretaría general de la Presidencia", "Secretaría general de gobierno", "Ministerio de Economía", "Fomento y Turismo", "Ministerio de desarrollo social", "Ministerio de Educación", "Ministerio de Justicia y derechos humanos", "Ministerio de Trabajo y previsión social", "Ministerio de Obras Públicas", "Ministerio de salud", "Ministerio de vivienda y urbanismo", "Ministerio de agricultura", "Ministerio de Mínería", "Ministerio de transporte y comunicaciones", "Ministerio de Bienes nacionales", "Ministerio de energía", "Ministerio de Medioambiente", "Ministerio del deporte", "Ministerio de la mujer y la equidad de género", "Ministerio de las culturas, las artes y el Patrimonio cultural" }));

        boxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione (...)", "Ministro/a", "Subsecretaría", "Asesoría", "Jefe de División", "Jefe de Departamento", "Jefe de Sección", "Jefe de Oficina", "Secretario/a Regional Ministerial (SEREMI)", "Personal Administrativo", "Personal de Prensa y Comunicaciones", "Personal Tecnologia", "Personal Auxiliar" }));

        lblSalarioEmpleado.setText("Salario");

        txtSalarioEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalarioEmpleadoActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRutEmpleado)
                    .addComponent(lblMinisterioEmpleado)
                    .addComponent(lblCargoEmpleado)
                    .addComponent(lblSalarioEmpleado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSalarioEmpleado)
                    .addComponent(boxMinisterio, 0, 1, Short.MAX_VALUE)
                    .addComponent(boxCargo, 0, 223, Short.MAX_VALUE)
                    .addComponent(txtRutEmpleado)
                    .addComponent(txtNombreEmpleado))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensajeEmergente)
                    .addComponent(lblModificarEmpleado))
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblModificarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensajeEmergente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEmpleado)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutEmpleado)
                    .addComponent(txtRutEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinisterioEmpleado)
                    .addComponent(boxMinisterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoEmpleado)
                    .addComponent(boxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalarioEmpleado)
                    .addComponent(txtSalarioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnVolver))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void txtNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpleadoActionPerformed

    private void txtRutEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutEmpleadoActionPerformed

    private void txtSalarioEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalarioEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalarioEmpleadoActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        // Recuperar los datos de los campos de texto
        String nombre = txtNombreEmpleado.getText().trim();
        String rut = txtRutEmpleado.getText().trim();
        String rutFormateado = AgregarEmpleado.formatearRut(rut);
        txtRutEmpleado.setText(rutFormateado);  // Actualizar el campo de texto con el formato
        
        String salarioTexto = txtSalarioEmpleado.getText().trim();
        
        // Verificar que los campos obligatorios no estén vacíos
        if (nombre.isEmpty() || rut.isEmpty() || salarioTexto.isEmpty()) {
            if(nombre.isEmpty()){
                txtNombreEmpleado.setBorder(this.borderRed);
            }
            else if(rut.isEmpty()){
                txtRutEmpleado.setBorder(this.borderRed);
            }
            else if(salarioTexto.isEmpty()){
                txtSalarioEmpleado.setBorder(this.borderRed);
            }
            lblMensajeEmergente.setText("Por favor, complete todos los campos obligatorios.");
            lblMensajeEmergente.setForeground(Color.red.darker().darker());
            return;  // Detener la ejecución si hay campos vacíos
        }
        
            // Convertir salario a número
        double salario = Double.parseDouble(salarioTexto);
            // Obtener el ministerio y el cargo seleccionados
        String ministerio = boxMinisterio.getSelectedItem().toString();
        String cargo = boxCargo.getSelectedItem().toString();
        
        empleado.setNombre(nombre);
        empleado.setRut(rutFormateado);
        empleado.setFechaNaci(empleado.getFechaNaci());
        empleado.setFechaContrato(empleado.getFechaContrato());
        empleado.setDepartamento(ministerio);
        empleado.setCargo(cargo);
        empleado.setSalario(salario);
        
        Menu.ActualizarCSVEmpleados();
        txtNombreEmpleado.setBorder(this.borderGreen);
        txtRutEmpleado.setBorder(this.borderGreen);
        txtSalarioEmpleado.setBorder(this.borderGreen);
        lblMensajeEmergente.setText("Empleado modificado correctamente.");
        lblMensajeEmergente.setForeground(Color.green.darker().darker());
        
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        // TODO add your handling code here:
        BuscarEmpleado.iniciar();
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    
    /**
     * @param empleado
     * @param
     */
    public static void iniciar(Empleado empleado) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // Create and display the fortxtSalarioEmpleado  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpleado(empleado).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCargo;
    private javax.swing.JComboBox<String> boxMinisterio;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblCargoEmpleado;
    private javax.swing.JLabel lblMensajeEmergente;
    private javax.swing.JLabel lblMinisterioEmpleado;
    private javax.swing.JLabel lblModificarEmpleado;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblRutEmpleado;
    private javax.swing.JLabel lblSalarioEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtRutEmpleado;
    private javax.swing.JTextField txtSalarioEmpleado;
    // End of variables declaration//GEN-END:variables
}